// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WeddingApp.Models;

namespace WeddingApp.Migrations
{
    [DbContext(typeof(RsvpContext))]
    [Migration("20180409041615_add-status-field")]
    partial class addstatusfield
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeddingApp.Models.Rsvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("InsertDate");

                    b.Property<int>("KidsCount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("PlusOne");

                    b.Property<string>("PlusOneName");

                    b.Property<int>("StatusId");

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("Id");

                    b.ToTable("RsvpItems");
                });
#pragma warning restore 612, 618
        }
    }
}
